env:
  node: true
  jest: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  import/extensions: 0
  no-underscore-dangle: ['error', { 'allow': ['__filename', '__dirname'] }]

parserOptions:
    ecmaVersion: 2020
