name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - name: npm install, build
      # Install and build project
      run: |
        make install
      # Add environment variables
      env:
        CI: true
    - name: Run linter
      # Run Linter
      run: |
        make lint
 
